server:
  port: 8083

spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8888
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}
  instance:
    preferIpAddress: true

# JWT Configuration (if using JWT for service-to-service auth)
jwt:
  secret: ${JWT_SECRET:your-256-bit-secret}
  expiration: 86400000  # 1 day in milliseconds
